name: Deploy Demo

on:
  push:
    branches: [main] # 当代码推送到 main 分支时触发

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          npm install  # 安装根目录依赖
          cd packages/web && npm install  # 确保子目录依赖也被安装

      - name: Build Demo
        # 指定到子目录运行构建命令
        run: npm run build --prefix packages/web

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/web/dist # 构建产物所在的位置
          branch: gh-pages # 部署到的目标分支